name: CD Build

on:
  release:
    types: [ published ]
    
env:
  PACKAGE_VERSION: ${{ github.event.release.tag_name }}

jobs:
  publish:
    name: Publish to Nuget
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project-name:
          - Azure.Storage.Table.Wrapper
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            7.0.x
      - name: Connect to GitHub Nuget Source
        run: dotnet nuget add source --username "Cheranga" --password ${{ secrets.NUGETPUSHKEY }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/Cheranga/index.json"
      
      - name: Create Package
        run: dotnet pack --configuration Release -p:ContinuousIntegrationBuild=true -p:PackageVersion=${{ env.PACKAGE_VERSION }} -p:PackageReleaseNotes="See https://github.com/Cheranga/libs-azure.storage.table.wrapper/releases/tag/${{ env.PACKAGE_VERSION }}" src/${{ matrix.project-name }}/${{ matrix.project-name }}.csproj
        
      - name: Push to GitHub Packages
        run: dotnet nuget push **\*.nupkg --api-key ${{ secrets.NUGETPUSHKEY }} --source github --skip-duplicate        
        
      - name: Push to Nuget
        if: ${{ github.ref == 'refs/heads/main' }}
        run: dotnet nuget push **\*.nupkg --api-key ${{ secrets.NUGETPACKAGEKEY }} --source 'https://api.nuget.org/v3/index.json' --skip-duplicate
          